#!/usr/bin/env bash

set -eux

STOW_FOLDERS=(ubuntu nvim ripgrep i3 i3status)

DOTFILES=$HOME/.dotfiles

pushd $DOTFILES
for folder in "${STOW_FOLDERS[@]}"; do
	stow --delete $folder
	stow $folder
done


# On Ubuntu XKB configuration lives in /usr/share/X11/xkb
# https://help.ubuntu.com/community/Custom%20keyboard%20layout%20definitions
XKB=xkb
TARGET=/usr/share/X11/xkb
echo "stow $XKB"
sudo stow \
    --target $TARGET \
    --delete \
    $XKB
sudo stow \
    --target $TARGET \
    $XKB

popd

